 steps:
 # build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/ci-cd:$COMMIT_SHA', '.']
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/ci-cd:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args: ['run', 'deploy', 'ci-cd', '--image', 'gcr.io/$PROJECT_ID/ci-cd:$COMMIT_SHA', '--region', 'us-central1', '--platform', 'managed', '--service-account=ci-cd-cloud-build@$PROJECT_ID.iam.gserviceaccount.com', '--set-env-vars=PROJECT_ID=sonia-project-1', '--set-env-vars=PROJECT_NAME=sonia-project-1']
 images:
 - 'gcr.io/$PROJECT_ID/ci-cd:$COMMIT_SHA'
